### ISSUE TITLE
The auth seems broken with current master

### ISSUE THREAD

**Issue by jmatsushita** [dereklieu/prose#4]
Hi Derek,

I just tried to deploy the latest changes but it doesn't seem to work anymore. Here's what use to happen with the previous version:

<img width="889" alt="screen shot 2016-07-07 at 07 19 34" src="https://cloud.githubusercontent.com/assets/356097/16653201/69b4f052-441d-11e6-93d9-323271913f22.png">

But with the current one:

![image](https://cloud.githubusercontent.com/assets/356097/16653259/be98ca9e-441d-11e6-80a5-6f5e3ddf6023.png)

Any ideas?

Cheers!

Jun

**Comment by dereklieu** [comment]
@jmatsushita Ah, let me take a look at this. Will post back with a fix.

**Comment by dereklieu** [comment]
@jmatsushita I realized I introduced a bug where the code would expect the string "gitlab" to be in the api url, or else it would default to github. That's fixed in the latest master and I've confirmed that it works.

**Comment by jmatsushita** [comment]
Confirmed that it's solved! Thanks!
